name: SBShop
version: '-1'
api-version: '1.15'
author: Ichii
main: fr.entasia.sbshop.Main
depend: [Libraries, SkyCore]

commands:
  shop:
    aliases: [shops, boutique]

  shopreload:
    aliases: [reloadshop]